# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *' # https://crontab.guru/#30_1_*_*_* (everyday at 0130)
permissions:
  contents: read
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f # v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue is stale because it has been open for 30 days with no activity and will be closed in 14 days unless you add a comment.

          stale-pr-message: >
            This PR is stale because it has been open for 30 days with no activity and will be closed in 14 days unless you add a comment.

          close-issue-message: >
            This issue was closed because it has been stalled for 14 days with no activity.

          close-pr-message: >
            This PR was closed because it has been stalled for 14 days with no activity.

          days-before-issue-stale: 30
          days-before-pr-stale: 30
          days-before-issue-close: 14
          days-before-pr-close: 14
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'dependencies,work-in-progress' # comma separated list of labels
          exempt-issue-labels: 'dependencies,work-in-progress' # comma separated list of labels
